//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowMediaWebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito_Detalle
    {
        public int id_detalle { get; set; }
        public int codigo_carrito { get; set; }
        public int codigo_producto { get; set; }
        public Nullable<int> cantidad_detalle { get; set; }
    
        public virtual Carrito_Compra Carrito_Compra { get; set; }
        public virtual Producto_Multimedia Producto_Multimedia { get; set; }
    }
}
