//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowMediaWebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devolucion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devolucion()
        {
            this.Multa = new HashSet<Multa>();
        }
    
        public int codigo_devolucion { get; set; }
        public string fecha_devolucion { get; set; }
        public string estado_devolucion { get; set; }
        public string descripcion_devolucion { get; set; }
        public int id_renta { get; set; }
    
        public virtual Renta Renta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Multa> Multa { get; set; }
    }
}
