//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowMediaWebMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlowMediaEntities : DbContext
    {
        public FlowMediaEntities()
            : base("name=FlowMediaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carrito_Compra> Carrito_Compra { get; set; }
        public virtual DbSet<Carrito_Detalle> Carrito_Detalle { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<Devolucion> Devolucion { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Multa> Multa { get; set; }
        public virtual DbSet<Producto_Multimedia> Producto_Multimedia { get; set; }
        public virtual DbSet<Renta> Renta { get; set; }

        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
