//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowMediaWebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multa
    {
        public int codigo_multa { get; set; }
        public string fecha_multa { get; set; }
        public string descripcion_multa { get; set; }
        public double monto_multa { get; set; }
        public string estado_multa { get; set; }
        public int codigo_devolucion { get; set; }
    
        public virtual Devolucion Devolucion { get; set; }
    }
}
