//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowMediaWebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto_Multimedia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto_Multimedia()
        {
            this.Carrito_Detalle = new HashSet<Carrito_Detalle>();
        }
    
        public int codigo_producto { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion_producto { get; set; }
        public string tipo_producto { get; set; }
        public double precio_producto { get; set; }
        public int cantidad_disponible_producto { get; set; }
        public double precio_producto_renta { get; set; }
        public string clasificacion_producto { get; set; }
        public string año_producto { get; set; }
        public Nullable<int> id_compra { get; set; }
        public int codigo_inventario { get; set; }
        public string imagen_producto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrito_Detalle> Carrito_Detalle { get; set; }
        public virtual Compra Compra { get; set; }
        public virtual Inventario Inventario { get; set; }
    }
}
